apiVersion: v1
kind: ConfigMap
metadata:
  name: front
  namespace: backup-testing-sample-flask-app
  labels:
    app: backup-testing-sample-flask
    component: front
    kind: ConfigMap
    version: 0.1.0
data:
  root_api: "http://back-backup-testing-sample-flask-app.apps.sand-4b7b.asten.maq"
